name       : libgig
version    : 4.2.0
release    : 5
source     :
    - https://download.linuxsampler.org/packages/libgig-4.2.0.tar.bz2 : 16229a46138b101eb9eda042c66d2cd652b1b3c9925a7d9577d52f2282f745ff
license    : LGPL-3.0-or-later
component  : multimedia.library
summary    : libgig is a library for dealing with Gigasampler, DLS, KORG, SoundFont
    and AKAI files.
description: |
    libgig is a C++ library for loading, modifying existing and creating new Gigasampler (.gig) files and DLS (Downloadable Sounds) Level 1/2 files, KORG sample based instruments (.KSF and .KMP files), SoundFont v2 (.sf2) files and AKAI sampler data.
builddeps  :
    - pkgconfig(sndfile)
setup      : |
    echo "/usr/lib64/libgig" > "libgig.conf"

    %configure --disable-static
build      : |
    %make
install    : |-
    %make_install

    # Thanks to archlinux for the fix for getting runtime dependencies to work:
    install -Dm0644 libgig.conf -t $installdir/usr/share/ld.so.conf.d/
