name       : libgig
version    : 4.1.0
release    : 2
source     :
    - http://download.linuxsampler.org/packages/libgig-4.1.0.tar.bz2 : 06a280278a323963042acdf13b092644cceb43ef367fcbb9ca7bbedff132bd0b
license    : LGPL-3.0
component  : multimedia.library
summary    : libgig is a library for dealing with Gigasampler, DLS, KORG, SoundFont and AKAI files.
description: |
    libgig is a C++ library for loading, modifying existing and creating new Gigasampler (.gig) files and DLS (Downloadable Sounds) Level 1/2 files, KORG sample based instruments (.KSF and .KMP files), SoundFont v2 (.sf2) files and AKAI sampler data.
builddeps  :
    - pkgconfig(sndfile)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
